user_1 = User.objects.create_user(username='user_1')
user_2 = User.objects.create_user(username='user_2')
author_1 = Author.objects.create(user=user_1)
author_2 = Author.objects.create(user=user_2)
category_1 = Category.objects.create(category_name='category_1')
category_2 = Category.objects.create(category_name='category_2')
category_3 = Category.objects.create(category_name='category_3')
category_4 = Category.objects.create(category_name='category_4')
paper_1 = Post.objects.create(author=user_1, post_type='Статья', categories=['category_1', 'category_2'])
paper_2 = Post.objects.create(author=user_2, post_type='Статья', categories=['category_1', 'category_3'])
news_1 = Post.objects.create(author=user_1, post_type='Новости', categories=['category_2', 'category_4'])
comment_1 = Comment.objects.create(post=paper_1, user=user_2)
comment_2 = Comment.objects.create(post=paper_2, user=user_1)
comment_3 = Comment.objects.create(post=news_1, user=user_2)
comment_4 = Comment.objects.create(post=news_1, user=user_2)
paper_1.like()
paper_2.like()
news_1.dislike()
comment_1.like()
comment_2.dislike()
comment_3.like()
comment_4.dislike()
user_1.update_rating()
user_2.update_rating()
User.objects.order_by(rating).values('username', 'rating')
Post.objects.filter(post_type='Статья').order_by(rating).values('post_datetime', 'author', 'rating', 'header', f'text[0:124]')
Comment.objects.all().values('comment_datetime', 'user', 'rating', 'text')